### ISSUE TITLE
v5 开发 todo

### ISSUE THREAD

**Issue by sdjdd** [leancloud/javascript-sdk#616]
- [x] 支持 `requestChangePhoneNumber` 和 `changePhoneNumber`
- [x] 实现 S3 file provider
- [ ] 将 `HTTPRequest` 和 `UploadRequest` 拆分到单独的模块中
- [x] 解决循环依赖
- [x] Batch add / get / update / delete
- [x] PushRouter
- [x] 由 APIPath 提供所有 API 的请求 path
- [ ] 支持使用 Push router 的 secondary 地址
- [ ] 支持保存 File 类型的数据（若未上传，则在保存时自动上传）
- [ ] 重构日志模块，以支持无法使用 debug 库的平台（还需整合 leancloud-realtime 的日志库）
- [ ] 使用 realtime-core + LiveQueryClient 实现 live query 的底层通信
- [ ] Adapter 完成 AbortSignal 相关的功能后，把开发用的 Adpater 换成正式的

#### 原计划重新实现 ws 连接，现改为使用 realtime-core 的实现
- [x] ~~优化 LiveQuery ws 连接数量~~
- [x] ~~定期（每 180 秒）发送心跳~~
- [x] ~~LiveQuery 确定一个子协议（目前用的缺省协议）~~
- [ ] ~~正确响应 `goaway` 命令（重新获取 push router ，连接新地址）~~

### 大项

- [ ] LiveQuery
- [ ] 应用内社交
- [ ] Push
- [ ] 解决 rollup typescript 插件的各种问题（实在不行就降级处理）
